---
language: python
python: 2.7

sudo: required

matrix:
  include:
    - os: linux
      dist: centos
      env: OS=centos

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Add roles path
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Basic role syntax check
  - ansible-playbook --connection=local tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
