---
- name: Disable Ctrl-Alt-Del reboot keybinding - sysvinit (EL5 and SLES 10/11)
  lineinfile:
    dest: /etc/inittab
    regexp: '^ca{{":"}}.*{{":"}}ctrlaltdel.*'
    line: 'ca{{":"}}12345{{":"}}ctrlaltdel{{":"}}/bin/echo "CTRL-ALT-DEL is disabled"'
    state: present
  when:
  - ansible_service_mgr == 'sysvinit'
  - ansible_virtualization_role is not defined or (ansible_virtualization_role is defined and ansible_virtualization_role != 'guest')

- name: Disable Ctrl-Alt-Del reboot keybinding - upstart (EL6)
  copy:
    src: control-alt-del.conf
    dest: /etc/init/control-alt-delete.conf
    owner: root
    group: root
    mode: 0644
  when:
  - ansible_service_mgr == 'upstart'
  - ansible_virtualization_role is not defined or (ansible_virtualization_role is defined and ansible_virtualization_role != 'guest')

- name: Disable Ctrl-Alt-Del reboot keybinding - systemd (EL7 and SLES12)
  systemd:
    name: ctrl-alt-del.target
    enabled: no
    masked: yes
    daemon_reload: yes
  when:
  - ansible_service_mgr == 'systemd'
  - ansible_virtualization_role is not defined or (ansible_virtualization_role is defined and ansible_virtualization_role != 'guest')

- name: Configure Magic SysRq
  sysctl:
    name: kernel.sysrq
    state: present
    value: "{{ magic_sysrq }}"
    sysctl_set: true
  notify: reload sysrq
  when:
  - ( ( ansible_distribution == 'RedHat' or ansible_distribution == 'Oracle Linux' or ansible_distribution == 'CentOS' ) and ansible_distribution_major_version|int >= 5 ) or ( ansible_distribution == 'SLES' and ansible_distribution_major_version|int == 12 )

- name: Configure Magic SysRq for SLES11
  lineinfile:
    dest: /etc/sysconfig/sysctl
    regexp: '^ENABLE_SYSRQ=.*'
    line: 'ENABLE_SYSRQ={{ magic_sysrq }}'
  when:
  - ansible_distribution == 'SLES'
  - ansible_distribution_major_version|int == 11 or ansible_distribution_major_version|int == 10
  notify: reload sysrq
