---
- name: Disable Ctrl-Alt-Del reboot keybinding - sysvinit (EL5 and SLES 10/11)
  lineinfile:
    dest: /etc/inittab
    regexp: '^ca{{":"}}.*{{":"}}ctrlaltdel.*'
    line: 'ca{{":"}}12345{{":"}}ctrlaltdel{{":"}}/bin/echo "CTRL-ALT-DEL is disabled"'
    state: present
  when:
  - ansible_service_mgr == 'sysvinit'
  - ansible_virtualization_role is not defined or (ansible_virtualization_role is defined and ansible_virtualization_role != 'guest')

- name: Disable Ctrl-Alt-Del reboot keybinding - upstart (EL6)
  copy:
    src: control-alt-del.conf
    dest: /etc/init/control-alt-delete.conf
    owner: root
    group: root
    mode: 0644
  when:
  - ansible_service_mgr == 'upstart'
  - ansible_virtualization_role is not defined or (ansible_virtualization_role is defined and ansible_virtualization_role != 'guest')

- name: Disable Ctrl-Alt-Del reboot keybinding - systemd (EL7 and SLES12)
  file:
    path: /etc/systemd/system/ctrl-alt-del.target
    state: link
    src: /dev/null
  when:
  - ansible_service_mgr == 'systemd'
  - ansible_virtualization_role is not defined or (ansible_virtualization_role is defined and ansible_virtualization_role != 'guest')

- name: Configure Magic SysRq
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^kernel.sysrq =.*'
    line: 'kernel.sysrq = {{ magic_sysrq }}'
  when:
  - ( ( ansible_distribution == 'RedHat' or ansible_distribution == 'Oracle Linux' or ansible_distribution == 'CentOS' ) and ansible_distribution_major_version|int >= 5 ) or ( ansible_distribution == 'SLES' and ansible_distribution_major_version|int == 12 )
  register: sysrq_1

- name: Configure Magic SysRq for SLES11
  lineinfile:
    dest: /etc/sysconfig/sysctl
    regexp: '^ENABLE_SYSRQ=.*'
    line: 'ENABLE_SYSRQ={{ magic_sysrq }}'
  when:
  - ansible_distribution == 'SLES'
  - ansible_distribution_major_version|int == 11 or ansible_distribution_major_version|int == 10
  register: sysrq_2

- name: Update current sysctl for Magic SysRq if needed
  command: "/sbin/sysctl -w kernel.sysrq={{ magic_sysrq }}"
  when: sysrq_1.changed or sysrq_2.changed
