---
- name: restart sshd
  service:
    name: "{{ ssh_service_name }}"
    state: restarted
    enabled: true

- name: restart audit daemon
  service:
    name: auditd
    state: restarted
    enabled: true
